use anyhow::Result;
use serde::{Deserialize, Serialize};

use super::GenerationCost;
use super::attempt::{ARTIFACT_ATTEMPT_CEILING, AttemptFault, AttemptLog, AttemptTally};
use super::candidate::{Sense, WordCandidate};
use super::labels::{SentenceLabelSelection, SentenceLabels};
use super::pair::LanguagePair;
use super::pass::CardRevision;

/// Largest number of cards one batch commits.
///
/// Generation is sequential single-flight at roughly 48 seconds and $0.19 per
/// card, so this ceiling keeps the slowest realistic run under two hours and
/// under twenty dollars. It bites only when a plan is first committed: a batch
/// committed before the limit existed still generates and republishes.
pub const MAX_PLAN_CARDS: usize = 80;

/// Artifact type produced for each card.
///
/// `Meta` is the rich text payload generated by the Gemini card pass before any
/// media artifact runs. Scene/Picture/Sound depend on it because they consume
/// the natural-language `target_sentence` to draw, illustrate, and speak.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Artifact {
    Meta,
    Scene,
    Picture,
    Sound,
}

impl Artifact {
    /// Return the stable label used in progress output.
    pub fn label(&self) -> &'static str {
        match self {
            Artifact::Meta => "meta",
            Artifact::Scene => "scene",
            Artifact::Picture => "picture",
            Artifact::Sound => "sound",
        }
    }
}

/// One settled artifact operation: its result, own spend, related-stage spend,
/// and the diagnosed cause when it failed.
pub(crate) type AccountedAttempt<T> = (
    Result<T>,
    Option<GenerationCost>,
    Vec<(Artifact, GenerationCost)>,
    Option<AttemptFault>,
);

/// One artifact operation together with its primary and related stage spend.
pub struct ArtifactAttempt<T> {
    result: Result<T>,
    cost: Option<GenerationCost>,
    related: Vec<(Artifact, GenerationCost)>,
    fault: Option<AttemptFault>,
}

impl<T> ArtifactAttempt<T> {
    /// Create one operation outcome with spend incurred by this operation.
    #[must_use]
    pub fn new(result: Result<T>, cost: Option<GenerationCost>) -> Self {
        Self {
            result,
            cost,
            related: Vec::new(),
            fault: None,
        }
    }

    /// Create one operation outcome for which Gemini reported no spend.
    #[must_use]
    pub fn unmetered(result: Result<T>) -> Self {
        Self::new(result, None)
    }

    /// Return the operation error when the artifact was not produced.
    #[must_use]
    pub fn error(&self) -> Option<&anyhow::Error> {
        self.result.as_ref().err()
    }

    /// Return the diagnosed cause attached to this failed operation.
    #[must_use]
    pub fn fault(&self) -> Option<&AttemptFault> {
        self.fault.as_ref()
    }

    /// Attach incremental spend that belongs to a related artifact stage.
    #[must_use]
    pub(crate) fn with_related_cost(mut self, artifact: Artifact, cost: GenerationCost) -> Self {
        self.related.push((artifact, cost));
        self
    }

    /// Attach the diagnosed cause of one failed operation.
    #[must_use]
    pub fn with_fault(mut self, fault: AttemptFault) -> Self {
        self.fault = Some(fault);
        self
    }

    /// Consume the operation into its result and primary incremental spend.
    pub fn into_parts(self) -> (Result<T>, Option<GenerationCost>) {
        (self.result, self.cost)
    }

    /// Consume the operation into its result, stage-aware spend, and cause.
    pub(crate) fn into_accounted_parts(self) -> AccountedAttempt<T> {
        (self.result, self.cost, self.related, self.fault)
    }

    /// Consume the operation and discard its accounting metadata.
    pub fn into_result(self) -> Result<T> {
        self.result
    }

    /// Transform the successful payload while retaining spend and failure context.
    #[must_use]
    pub fn map<U>(self, transform: impl FnOnce(T) -> U) -> ArtifactAttempt<U> {
        ArtifactAttempt {
            result: self.result.map(transform),
            cost: self.cost,
            related: self.related,
            fault: self.fault,
        }
    }
}

/// File metadata attached to one completed artifact.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ArtifactFile {
    name: String,
    path: std::path::PathBuf,
    size: String,
    cached: bool,
    cost: Option<GenerationCost>,
}

impl ArtifactFile {
    /// Create one artifact file descriptor with full filesystem path.
    pub fn new(
        name: impl Into<String>,
        path: impl Into<std::path::PathBuf>,
        size: impl Into<String>,
        cached: bool,
    ) -> Self {
        Self {
            name: name.into(),
            path: path.into(),
            size: size.into(),
            cached,
            cost: None,
        }
    }

    /// Return the display filename.
    pub fn name(&self) -> &str {
        self.name.as_str()
    }

    /// Return the absolute filesystem path for this artifact, if any. Used by
    /// the click handler to open the artifact with the system default app.
    pub fn path(&self) -> &std::path::Path {
        self.path.as_path()
    }

    /// Return the human-readable file size.
    pub fn size(&self) -> &str {
        self.size.as_str()
    }

    /// Return whether this artifact came from cache.
    pub fn cached(&self) -> bool {
        self.cached
    }

    /// Return the estimated Gemini cost attached to this artifact.
    pub fn cost(&self) -> Option<GenerationCost> {
        self.cost
    }

    /// Return the file with an estimated Gemini cost attached.
    pub fn with_cost(mut self, cost: GenerationCost) -> Self {
        self.cost = Some(cost);
        self
    }
}

/// Per-artifact state for one card.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ArtifactSlot {
    kind: Artifact,
    ready: bool,
    discarded: bool,
    attempts: AttemptLog,
    file: Option<ArtifactFile>,
    cost: Option<GenerationCost>,
}

impl ArtifactSlot {
    /// Create one fresh slot for the given artifact kind.
    pub fn fresh(kind: Artifact) -> Self {
        Self {
            kind,
            ready: false,
            discarded: false,
            attempts: AttemptLog::new(ARTIFACT_ATTEMPT_CEILING),
            file: None,
            cost: None,
        }
    }

    /// Return the artifact kind.
    pub fn kind(&self) -> Artifact {
        self.kind
    }

    /// Return whether the artifact is ready.
    pub fn ready(&self) -> bool {
        self.ready
    }

    /// Return whether this artifact was explicitly discarded by the user.
    pub fn discarded(&self) -> bool {
        self.discarded
    }

    /// Return whether this slot no longer needs queue work.
    pub fn complete(&self) -> bool {
        self.ready || self.discarded || self.failed_terminally()
    }

    /// Return the attempt tally.
    pub fn tally(&self) -> AttemptTally {
        self.attempts.tally()
    }

    /// Return why each spent attempt failed, in attempt order.
    pub fn faults(&self) -> &[AttemptFault] {
        self.attempts.faults()
    }

    /// Return why the most recently spent attempt failed.
    pub fn latest_fault(&self) -> Option<&AttemptFault> {
        self.attempts.latest()
    }

    /// Return completed artifact file metadata, if available.
    pub fn file(&self) -> Option<&ArtifactFile> {
        self.file.as_ref()
    }

    /// Return the estimated Gemini cost for this artifact slot.
    pub fn cost(&self) -> Option<GenerationCost> {
        self.cost
            .or_else(|| self.file.as_ref().and_then(ArtifactFile::cost))
    }

    /// Return the slot as ready.
    pub fn succeeded(mut self) -> Self {
        self.ready = true;
        self.discarded = false;
        self
    }

    /// Return the slot as ready with file metadata.
    pub fn succeeded_with(mut self, file: ArtifactFile) -> Self {
        self.ready = true;
        self.discarded = false;
        if let Some(cost) = file.cost() {
            self.cost = Some(cost);
        }
        self.file = Some(file);
        self
    }

    /// Return the slot after a failed attempt whose cause was not diagnosed.
    pub fn attempted(mut self) -> Self {
        self.attempts = self.attempts.spent();
        self
    }

    /// Return the slot after a failed attempt that failed for `fault`.
    pub fn faulted(mut self, fault: AttemptFault) -> Self {
        self.attempts = self.attempts.faulted(fault);
        self
    }

    /// Return the slot after a failed attempt with cumulative known spend.
    pub fn attempted_with(self, cost: GenerationCost) -> Self {
        self.attempted().accounted(cost)
    }

    /// Return a fresh retry slot while retaining already billed spend.
    pub fn retry(self) -> Self {
        let kind = self.kind;
        let cost = self.cost();
        let slot = Self::fresh(kind);
        match cost {
            Some(cost) => slot.accounted(cost),
            None => slot,
        }
    }

    /// Return the slot with its latest cumulative known spend.
    pub(crate) fn accounted(mut self, cost: GenerationCost) -> Self {
        self.cost = Some(cost);
        self
    }

    /// Return the slot as explicitly discarded by the user.
    pub fn discard(mut self) -> Self {
        let cost = self.cost();
        self.ready = false;
        self.discarded = true;
        self.file = None;
        self.cost = cost;
        self
    }

    /// Return whether retry budget has been exhausted without success.
    pub fn failed_terminally(&self) -> bool {
        !self.ready && !self.discarded && self.attempts.tally().exhausted()
    }
}

/// The four per-card artifact slots bundled together.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CardArtifacts {
    meta: ArtifactSlot,
    scene: ArtifactSlot,
    picture: ArtifactSlot,
    sound: ArtifactSlot,
}

/// Persistable per-artifact spend incurred by one generation session.
#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct ArtifactCosts {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    meta: Option<GenerationCost>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    scene: Option<GenerationCost>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    picture: Option<GenerationCost>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    sound: Option<GenerationCost>,
}

impl ArtifactCosts {
    /// Snapshot the session-scoped spend currently attached to artifact slots.
    #[must_use]
    pub fn from_artifacts(artifacts: &CardArtifacts) -> Self {
        Self {
            meta: artifacts.meta().cost(),
            scene: artifacts.scene().cost(),
            picture: artifacts.picture().cost(),
            sound: artifacts.sound().cost(),
        }
    }

    /// Return the session-scoped spend recorded for one artifact.
    #[must_use]
    pub fn cost(&self, artifact: Artifact) -> Option<GenerationCost> {
        match artifact {
            Artifact::Meta => self.meta,
            Artifact::Scene => self.scene,
            Artifact::Picture => self.picture,
            Artifact::Sound => self.sound,
        }
    }

    /// Return the costs after charging one artifact an additional amount.
    #[must_use]
    pub fn charged(mut self, artifact: Artifact, delta: GenerationCost) -> Self {
        let total = self.cost(artifact).unwrap_or_default() + delta;
        match artifact {
            Artifact::Meta => self.meta = Some(total),
            Artifact::Scene => self.scene = Some(total),
            Artifact::Picture => self.picture = Some(total),
            Artifact::Sound => self.sound = Some(total),
        }
        self
    }

    /// Return whether no provider spend is recorded for this session card.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.meta.is_none()
            && self.scene.is_none()
            && self.picture.is_none()
            && self.sound.is_none()
    }

    fn hydrate(&self, artifacts: CardArtifacts) -> CardArtifacts {
        CardArtifacts::from_parts(
            hydrate_cost(artifacts.meta().clone(), self.meta),
            hydrate_cost(artifacts.scene().clone(), self.scene),
            hydrate_cost(artifacts.picture().clone(), self.picture),
            hydrate_cost(artifacts.sound().clone(), self.sound),
        )
    }
}

fn hydrate_cost(slot: ArtifactSlot, cost: Option<GenerationCost>) -> ArtifactSlot {
    match cost {
        Some(cost) => slot.accounted(cost),
        None => slot,
    }
}

impl Default for CardArtifacts {
    /// Return four fresh slots for a new card.
    fn default() -> Self {
        Self {
            meta: ArtifactSlot::fresh(Artifact::Meta),
            scene: ArtifactSlot::fresh(Artifact::Scene),
            picture: ArtifactSlot::fresh(Artifact::Picture),
            sound: ArtifactSlot::fresh(Artifact::Sound),
        }
    }
}

impl CardArtifacts {
    /// Compose one artifacts bundle from four explicit slots.
    pub fn from_parts(
        meta: ArtifactSlot,
        scene: ArtifactSlot,
        picture: ArtifactSlot,
        sound: ArtifactSlot,
    ) -> Self {
        Self {
            meta,
            scene,
            picture,
            sound,
        }
    }

    /// Return the slot for `Artifact::Meta`.
    pub fn meta(&self) -> &ArtifactSlot {
        &self.meta
    }

    /// Return the slot for `Artifact::Scene`.
    pub fn scene(&self) -> &ArtifactSlot {
        &self.scene
    }

    /// Return the slot for `Artifact::Picture`.
    pub fn picture(&self) -> &ArtifactSlot {
        &self.picture
    }

    /// Return the slot for `Artifact::Sound`.
    pub fn sound(&self) -> &ArtifactSlot {
        &self.sound
    }

    /// Return whether every artifact is ready.
    pub fn all_ready(&self) -> bool {
        self.meta.ready() && self.scene.ready() && self.picture.ready() && self.sound.ready()
    }

    /// Return whether any artifact failed terminally.
    pub fn has_failed(&self) -> bool {
        self.meta.failed_terminally()
            || self.scene.failed_terminally()
            || self.picture.failed_terminally()
            || self.sound.failed_terminally()
    }

    /// Return the known Gemini cost across all artifact slots.
    pub fn cost(&self) -> Option<GenerationCost> {
        let costs = [self.meta(), self.scene(), self.picture(), self.sound()]
            .into_iter()
            .filter_map(ArtifactSlot::cost)
            .collect::<Vec<_>>();
        if costs.is_empty() {
            return None;
        }
        Some(costs.into_iter().sum())
    }
}

/// The rich card content produced by the Gemini meta-generation pass.
///
/// Mirrors the `VocabularyEntry` schema. Filled once per draft after the user
/// confirms the understanding pass, and updated when the learner submits the
/// inline sentence editor to refine a single card.
#[derive(Clone, Debug, Deserialize, Eq, Hash, PartialEq, Serialize)]
pub struct CardMeta {
    pronunciation: String,
    transcription: String,
    meaning: String,
    importance: u8,
    source_sentence: String,
    source_highlight: String,
    source_hint: String,
    source_context: String,
    target_sentence: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    labels: Option<SentenceLabels>,
    #[serde(default, skip_serializing_if = "generated_meta")]
    rewritten: bool,
}

fn generated_meta(rewritten: &bool) -> bool {
    !*rewritten
}

impl CardMeta {
    /// Create one card meta. Caller is responsible for validating that
    /// `source_highlight` is a substring of `source_sentence`.
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        pronunciation: impl Into<String>,
        transcription: impl Into<String>,
        meaning: impl Into<String>,
        importance: u8,
        source_sentence: impl Into<String>,
        source_highlight: impl Into<String>,
        source_hint: impl Into<String>,
        source_context: impl Into<String>,
        target_sentence: impl Into<String>,
    ) -> Self {
        Self {
            pronunciation: pronunciation.into(),
            transcription: transcription.into(),
            meaning: meaning.into(),
            importance,
            source_sentence: source_sentence.into(),
            source_highlight: source_highlight.into(),
            source_hint: source_hint.into(),
            source_context: source_context.into(),
            target_sentence: target_sentence.into(),
            labels: None,
            rewritten: false,
        }
    }

    /// Return the IPA transcription of the term.
    pub fn pronunciation(&self) -> &str {
        self.pronunciation.as_str()
    }

    /// Return the IPA transcription of the full target sentence.
    pub fn transcription(&self) -> &str {
        self.transcription.as_str()
    }

    /// Return the source-language translation of the term.
    pub fn meaning(&self) -> &str {
        self.meaning.as_str()
    }

    /// Return the importance score (1..=10).
    pub fn importance(&self) -> u8 {
        self.importance
    }

    /// Return the source-language translation of the target sentence.
    pub fn source_sentence(&self) -> &str {
        self.source_sentence.as_str()
    }

    /// Return the substring of `source_sentence` that translates the term.
    pub fn source_highlight(&self) -> &str {
        self.source_highlight.as_str()
    }

    /// Return the one-sentence memory cue in source language.
    pub fn source_hint(&self) -> &str {
        self.source_hint.as_str()
    }

    /// Return the multi-sentence usage explanation in source language.
    pub fn source_context(&self) -> &str {
        self.source_context.as_str()
    }

    /// Return the metadata with a locally normalized usage explanation installed.
    #[must_use]
    pub fn with_source_context(mut self, source_context: impl Into<String>) -> Self {
        self.source_context = source_context.into();
        self
    }

    /// Return the metadata with only the reviewed term and sentence IPA replaced.
    #[must_use]
    pub(crate) fn with_phonetics(
        mut self,
        pronunciation: impl Into<String>,
        transcription: impl Into<String>,
    ) -> Self {
        self.pronunciation = pronunciation.into();
        self.transcription = transcription.into();
        self
    }

    /// Return the natural example sentence in target language.
    pub fn target_sentence(&self) -> &str {
        self.target_sentence.as_str()
    }

    /// Return the optional generated sentence attribution.
    #[must_use]
    pub fn sentence_labels(&self) -> Option<&SentenceLabels> {
        self.labels.as_ref()
    }

    /// Return the metadata with generated sentence attribution installed.
    #[must_use]
    pub fn with_sentence_labels(mut self, labels: SentenceLabels) -> Self {
        self.labels = Some(labels);
        self
    }

    /// Return whether this sentence was minted for a learner's own rewrite of
    /// one card, rather than by the batch that generated everything.
    ///
    /// This is what lets a screen show which single card was touched among its
    /// untouched neighbours, so a batch-wide level or type — pinned once for
    /// every card at generation — deliberately does not set it.
    #[must_use]
    pub fn rewritten(&self) -> bool {
        self.rewritten
    }

    /// Return the metadata marked as the product of a per-card rewrite.
    #[must_use]
    pub fn marked_rewritten(mut self) -> Self {
        self.rewritten = true;
        self
    }
}

/// A durable full-card rewrite queued as the metadata step of generation.
#[derive(Clone, Debug, Deserialize, Eq, Hash, PartialEq, Serialize)]
pub struct CardRewrite {
    previous: Option<CardMeta>,
    selection: SentenceLabelSelection,
    note: String,
    #[serde(default = "rewrite_started")]
    started: bool,
}

impl CardRewrite {
    /// Create an activated rewrite from the prior metadata, working labels, and free note.
    #[must_use]
    pub fn new(
        previous: Option<CardMeta>,
        selection: SentenceLabelSelection,
        note: impl Into<String>,
    ) -> Self {
        Self {
            previous,
            selection,
            note: note.into(),
            started: true,
        }
    }

    /// Return the metadata visible before the rewrite started.
    #[must_use]
    pub fn previous(&self) -> Option<&CardMeta> {
        self.previous.as_ref()
    }

    /// Return the changed and preserved values requested for the rewrite.
    #[must_use]
    pub fn selection(&self) -> &SentenceLabelSelection {
        &self.selection
    }

    /// Return the learner's optional free-form correction.
    #[must_use]
    pub fn note(&self) -> &str {
        self.note.as_str()
    }

    /// Return whether batch generation has activated this rewrite.
    #[must_use]
    pub fn started(&self) -> bool {
        self.started
    }

    fn staging(mut self) -> Self {
        self.started = false;
        self
    }

    /// Return this durable rewrite activated for the next generation batch.
    #[must_use]
    pub fn activate(mut self) -> Self {
        self.started = true;
        self
    }
}

fn rewrite_started() -> bool {
    true
}

/// Where one card stands in the batch, derived from its artifacts and rewrite.
///
/// The order of the checks is load-bearing. A staged rewrite sits on top of
/// intact artifacts, so `all_ready` still answers true while the card waits to
/// be re-rolled, and testing it first is what keeps an adjusted card from
/// reporting as ready. `Working` then covers both the queue and the single
/// card the engine currently runs.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CardPhase {
    /// Carries a staged rewrite that no generation run has activated yet.
    Adjusted,
    /// Spent every attempt on at least one artifact without succeeding.
    Failed,
    /// Still owes at least one artifact.
    Working,
    /// Holds every artifact.
    Ready,
}

/// One card draft inside the current batch.
///
/// `meta` starts as `None` and is filled by the Gemini meta pass that runs
/// before scene/picture/sound. The bridge to `VocabularyEntry` requires a meta.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CardDraft {
    term: String,
    reviewed_senses: Vec<Sense>,
    sense_priorities: Vec<usize>,
    pair: LanguagePair,
    meta: Option<CardMeta>,
    meta_request: Option<SentenceLabelSelection>,
    rewrite: Option<CardRewrite>,
    artifacts: CardArtifacts,
}

impl CardDraft {
    /// Create one draft with no meta yet.
    pub fn new(
        term: impl Into<String>,
        understanding: impl Into<String>,
        pair: LanguagePair,
    ) -> Self {
        Self {
            term: term.into(),
            reviewed_senses: vec![Sense::plain(understanding)],
            sense_priorities: Vec::new(),
            pair,
            meta: None,
            meta_request: None,
            rewrite: None,
            artifacts: CardArtifacts::default(),
        }
    }

    /// Create one draft from a reviewed candidate and the sense chosen for this card.
    ///
    /// The chosen sense is placed first. Every other reviewed sense follows in
    /// the candidate's original display order, with its optional tag intact.
    #[must_use]
    pub fn from_candidate(candidate: &WordCandidate, selected: usize, pair: LanguagePair) -> Self {
        let chosen = candidate
            .senses()
            .get(selected)
            .unwrap_or_else(|| panic!("invariant: selected sense index {selected} must exist"));
        let reviewed_senses = std::iter::once(chosen.clone())
            .chain(
                candidate
                    .senses()
                    .iter()
                    .enumerate()
                    .filter(|(index, _)| *index != selected)
                    .map(|(_, sense)| sense.clone()),
            )
            .collect();
        Self::new(candidate.term(), chosen.understanding(), pair)
            .with_reviewed_senses(reviewed_senses)
            .with_sense_priorities(
                std::iter::once(selected)
                    .chain((0..candidate.senses().len()).filter(|index| *index != selected))
                    .collect(),
            )
    }

    /// Return the draft carrying a non-empty, selected-first reviewed sense list.
    #[must_use]
    pub(crate) fn with_reviewed_senses(mut self, reviewed_senses: Vec<Sense>) -> Self {
        assert!(
            !reviewed_senses.is_empty(),
            "invariant: a card draft must keep at least one reviewed sense"
        );
        self.reviewed_senses = reviewed_senses;
        self.sense_priorities.clear();
        self
    }

    /// Restore the original relative priority without changing selected-first cache identity.
    #[must_use]
    pub(crate) fn with_sense_priorities(mut self, priorities: Vec<usize>) -> Self {
        self.sense_priorities = normalized_priorities(priorities, self.reviewed_senses.len());
        self
    }

    /// Return the stable zero-based priority of one currently displayed reviewed sense.
    #[must_use]
    pub(crate) fn sense_priority(&self, index: usize) -> usize {
        assert!(
            index < self.reviewed_senses.len(),
            "invariant: a prioritized sense must exist"
        );
        self.sense_priorities.get(index).copied().unwrap_or(index)
    }

    /// Return the primary term.
    pub fn term(&self) -> &str {
        self.term.as_str()
    }

    /// Return the understanding sentence carried over from the intake pass.
    pub fn understanding(&self) -> &str {
        self.reviewed_senses[0].understanding()
    }

    /// Return every reviewed sense with the one chosen for this card first.
    #[must_use]
    pub fn reviewed_senses(&self) -> &[Sense] {
        self.reviewed_senses.as_slice()
    }

    /// Return the language pair locked into the card.
    pub fn pair(&self) -> &LanguagePair {
        &self.pair
    }

    /// Return the rich meta if it has been generated.
    pub fn meta(&self) -> Option<&CardMeta> {
        self.meta.as_ref()
    }

    /// Return the pending label request for this draft's first metadata pass.
    #[must_use]
    pub fn meta_request(&self) -> Option<&SentenceLabelSelection> {
        self.meta_request.as_ref()
    }

    /// Return the draft carrying one label request for its first metadata pass.
    #[must_use]
    pub fn requesting_meta(mut self, selection: SentenceLabelSelection) -> Self {
        self.meta_request = Some(selection);
        self
    }

    /// Return the queued full-card rewrite when metadata must be regenerated.
    #[must_use]
    pub fn rewrite(&self) -> Option<&CardRewrite> {
        self.rewrite.as_ref()
    }

    /// Return the queued rewrite only while it still waits for batch activation.
    #[must_use]
    pub fn staged_rewrite(&self) -> Option<&CardRewrite> {
        self.rewrite.as_ref().filter(|rewrite| !rewrite.started())
    }

    /// Return whether this card's sentence labels can be edited: it has the
    /// metadata they describe, and no rewrite of its own is already running.
    #[must_use]
    pub fn tunable(&self) -> bool {
        self.meta.is_some() && (self.rewrite.is_none() || self.staged_rewrite().is_some())
    }

    /// Return where this card stands in the batch.
    #[must_use]
    pub fn phase(&self) -> CardPhase {
        if self.staged_rewrite().is_some() {
            CardPhase::Adjusted
        } else if self.artifacts.has_failed() {
            CardPhase::Failed
        } else if self.artifacts.all_ready() {
            CardPhase::Ready
        } else {
            CardPhase::Working
        }
    }

    /// Return the per-artifact state.
    pub fn artifacts(&self) -> &CardArtifacts {
        &self.artifacts
    }

    /// Return the draft with the rich meta installed after the Gemini pass.
    /// Marks the Meta artifact slot as ready so the engine moves on to media
    /// steps. When `file` is provided the slot keeps a clickable file handle so
    /// the user can open the persisted JSON from the step list.
    pub fn with_meta(self, meta: CardMeta, file: Option<ArtifactFile>) -> Self {
        let meta_slot = match file {
            Some(file) => self.artifacts.meta().clone().succeeded_with(file),
            None => self.artifacts.meta().clone().succeeded(),
        };
        let artifacts = CardArtifacts::from_parts(
            meta_slot,
            self.artifacts.scene().clone(),
            self.artifacts.picture().clone(),
            self.artifacts.sound().clone(),
        );
        Self {
            term: self.term,
            reviewed_senses: self.reviewed_senses,
            sense_priorities: self.sense_priorities,
            pair: self.pair,
            meta: Some(meta),
            meta_request: None,
            rewrite: None,
            artifacts,
        }
    }

    /// Return the draft with a metadata revision installed after a rewrite attempt.
    /// A changed term retains only its newly confirmed, untagged understanding.
    #[must_use]
    pub fn with_revision(self, revision: CardRevision, file: Option<ArtifactFile>) -> Self {
        let (term, understanding, meta) = revision.into_parts();
        let priorities = (0..self.reviewed_senses.len())
            .map(|index| self.sense_priority(index))
            .collect();
        let (reviewed_senses, sense_priorities) = synchronized_senses(
            self.reviewed_senses,
            priorities,
            self.term.as_str(),
            term.as_str(),
            understanding.as_str(),
        );
        let meta_slot = match file {
            Some(file) => self.artifacts.meta().clone().succeeded_with(file),
            None => self.artifacts.meta().clone().succeeded(),
        };
        let artifacts = CardArtifacts::from_parts(
            meta_slot,
            self.artifacts.scene().clone(),
            self.artifacts.picture().clone(),
            self.artifacts.sound().clone(),
        );
        Self {
            term,
            reviewed_senses,
            sense_priorities,
            pair: self.pair,
            meta: Some(meta),
            meta_request: None,
            rewrite: None,
            artifacts,
        }
    }

    /// Return the draft with a rewrite staged beside its current metadata and artifacts.
    #[must_use]
    pub fn staging_rewrite(
        self,
        selection: SentenceLabelSelection,
        note: impl Into<String>,
    ) -> Self {
        let note = note.into();
        let previous = self
            .rewrite
            .as_ref()
            .and_then(|rewrite| rewrite.previous.clone())
            .or_else(|| self.meta.clone());
        let baseline = previous
            .as_ref()
            .and_then(CardMeta::sentence_labels)
            .map(SentenceLabelSelection::from_labels)
            .unwrap_or_default();
        let unchanged = selection == baseline;
        let rewrite = (!unchanged || !note.trim().is_empty())
            .then(|| CardRewrite::new(previous, selection, note).staging());
        Self {
            term: self.term,
            reviewed_senses: self.reviewed_senses,
            sense_priorities: self.sense_priorities,
            pair: self.pair,
            meta: self.meta,
            meta_request: None,
            rewrite,
            artifacts: self.artifacts,
        }
    }

    /// Return the draft with its staged rewrite activated as a fresh metadata run.
    #[must_use]
    pub fn starting_rewrite(self) -> Self {
        let Some(rewrite) = self.rewrite.as_ref() else {
            return self;
        };
        if rewrite.started() {
            return self;
        }
        let costs = ArtifactCosts::from_artifacts(&self.artifacts);
        let fresh = CardArtifacts::default();
        Self {
            term: self.term,
            reviewed_senses: self.reviewed_senses,
            sense_priorities: self.sense_priorities,
            pair: self.pair,
            meta: None,
            meta_request: None,
            rewrite: self.rewrite.map(CardRewrite::activate),
            artifacts: costs.hydrate(fresh),
        }
    }

    /// Return the draft immediately queued for a full rewrite through metadata retries.
    #[must_use]
    pub fn rewriting(self, selection: SentenceLabelSelection, note: impl Into<String>) -> Self {
        self.staging_rewrite(selection, note).starting_rewrite()
    }

    /// Return the draft with a durable rewrite request restored from a session.
    #[must_use]
    pub fn with_rewrite(mut self, rewrite: Option<CardRewrite>) -> Self {
        if let Some(previous) = rewrite
            .as_ref()
            .filter(|request| !request.started())
            .and_then(CardRewrite::previous)
            .cloned()
        {
            let artifacts = CardArtifacts::from_parts(
                self.artifacts.meta().clone().succeeded(),
                self.artifacts.scene().clone(),
                self.artifacts.picture().clone(),
                self.artifacts.sound().clone(),
            );
            self.meta = Some(previous);
            self.artifacts = artifacts;
        }
        if rewrite.is_some() {
            self.meta_request = None;
        }
        self.rewrite = rewrite;
        self
    }

    /// Return the draft after a per-card correction.
    ///
    /// The correction may rewrite the term (typo fix), the understanding
    /// (sense or form change), and the rich meta. Artifacts reset because
    /// scene/picture/sound depend on the meta. When the caller has already
    /// persisted the new meta to disk, the resulting `ArtifactFile` lands on
    /// the meta slot so the meta row keeps its clickable file label.
    /// A changed term retains only its newly confirmed, untagged understanding.
    pub fn recomposed(
        self,
        term: impl Into<String>,
        understanding: impl Into<String>,
        meta: CardMeta,
        file: Option<ArtifactFile>,
    ) -> Self {
        let term = term.into();
        let understanding = understanding.into();
        let priorities = (0..self.reviewed_senses.len())
            .map(|index| self.sense_priority(index))
            .collect();
        let (reviewed_senses, sense_priorities) = synchronized_senses(
            self.reviewed_senses,
            priorities,
            self.term.as_str(),
            term.as_str(),
            understanding.as_str(),
        );
        let meta_slot = match file {
            Some(file) => ArtifactSlot::fresh(Artifact::Meta).succeeded_with(file),
            None => ArtifactSlot::fresh(Artifact::Meta).succeeded(),
        };
        let artifacts = CardArtifacts::from_parts(
            meta_slot,
            ArtifactSlot::fresh(Artifact::Scene),
            ArtifactSlot::fresh(Artifact::Picture),
            ArtifactSlot::fresh(Artifact::Sound),
        );
        Self {
            term,
            reviewed_senses,
            sense_priorities,
            pair: self.pair,
            meta: Some(meta),
            meta_request: None,
            rewrite: None,
            artifacts,
        }
    }

    /// Return the draft with a different artifacts bundle (for retry/success events).
    pub fn with_artifacts(self, artifacts: CardArtifacts) -> Self {
        Self {
            term: self.term,
            reviewed_senses: self.reviewed_senses,
            sense_priorities: self.sense_priorities,
            pair: self.pair,
            meta: self.meta,
            meta_request: self.meta_request,
            rewrite: self.rewrite,
            artifacts,
        }
    }

    /// Return the draft with persisted session-scoped artifact spend restored.
    #[must_use]
    pub fn with_costs(self, costs: ArtifactCosts) -> Self {
        let artifacts = costs.hydrate(self.artifacts);
        Self {
            term: self.term,
            reviewed_senses: self.reviewed_senses,
            sense_priorities: self.sense_priorities,
            pair: self.pair,
            meta: self.meta,
            meta_request: self.meta_request,
            rewrite: self.rewrite,
            artifacts,
        }
    }
}

fn synchronized_senses(
    mut senses: Vec<Sense>,
    priorities: Vec<usize>,
    previous: &str,
    term: &str,
    understanding: &str,
) -> (Vec<Sense>, Vec<usize>) {
    if previous != term {
        return (vec![Sense::plain(understanding)], Vec::new());
    }
    let selected = senses
        .iter()
        .position(|sense| sense.matches(understanding))
        .unwrap_or_else(|| {
            senses[0] = Sense::plain(understanding);
            0
        });
    let mut ranked = priorities.into_iter().zip(senses).collect::<Vec<_>>();
    let chosen = ranked.remove(selected);
    ranked.sort_by_key(|(priority, _)| *priority);
    ranked.insert(0, chosen);
    let (priorities, senses): (Vec<_>, Vec<_>) = ranked.into_iter().unzip();
    let priorities = normalized_priorities(priorities, senses.len());
    (senses, priorities)
}

fn normalized_priorities(priorities: Vec<usize>, count: usize) -> Vec<usize> {
    let mut sorted = priorities.clone();
    sorted.sort_unstable();
    assert!(
        sorted.iter().copied().eq(0..count),
        "invariant: sense priorities must form one complete ordered inventory"
    );
    if priorities.iter().copied().eq(0..count) {
        Vec::new()
    } else {
        priorities
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn meta() -> CardMeta {
        CardMeta::new(
            "ka.naʁ",
            "lə ka.naʁ vɔl",
            "duck",
            6,
            "The duck flies.",
            "duck",
            "Think of the bird.",
            "A common animal noun.",
            "Le canard vole.",
        )
    }

    fn finished_artifacts() -> CardArtifacts {
        CardArtifacts::from_parts(
            ArtifactSlot::fresh(Artifact::Meta).succeeded(),
            ArtifactSlot::fresh(Artifact::Scene).succeeded(),
            ArtifactSlot::fresh(Artifact::Picture).succeeded(),
            ArtifactSlot::fresh(Artifact::Sound).succeeded(),
        )
    }

    #[test]
    fn a_staged_rewrite_outranks_the_finished_artifacts_behind_it() {
        let adjusted = CardDraft::new(
            "chouette",
            "owl, and also nice",
            LanguagePair::new("en", "fr"),
        )
        .with_artifacts(finished_artifacts())
        .staging_rewrite(SentenceLabelSelection::empty(), "make it lighter");
        assert_eq!(
            adjusted.phase(),
            CardPhase::Adjusted,
            "a card waiting to be re-rolled reported itself as finished"
        );
    }

    #[test]
    fn a_card_holding_every_artifact_is_finished() {
        let built = CardDraft::new("flâner", "to stroll", LanguagePair::new("en", "fr"))
            .with_artifacts(finished_artifacts());
        assert_eq!(
            built.phase(),
            CardPhase::Ready,
            "a fully built card was still counted as owing work"
        );
    }

    #[test]
    fn the_legacy_constructor_keeps_one_reviewed_sense() {
        let draft = CardDraft::new("canard", "a duck", LanguagePair::new("en", "fr"));
        assert_eq!(
            draft.reviewed_senses(),
            &[Sense::plain("a duck")],
            "the singleton constructor stopped retaining its understanding as a reviewed sense"
        );
    }

    #[test]
    fn repeated_revisions_cannot_rank_a_previous_rare_choice_above_common_alternatives() {
        let senses = (1..=6)
            .map(|rank| Sense::tagged(format!("meaning {rank}"), format!("tag {rank}")))
            .collect::<Vec<_>>();
        let candidate = WordCandidate::with_senses("bank", senses.clone(), 5, true);
        let mut draft = CardDraft::from_candidate(&candidate, 5, LanguagePair::new("en", "ru"));
        let mut actual = vec![draft.reviewed_senses().to_vec()];
        for selected in [4, 0] {
            draft = draft.with_revision(
                CardRevision::new("bank", senses[selected].understanding(), meta()),
                None,
            );
            actual.push(draft.reviewed_senses().to_vec());
        }
        let expected = [5, 4, 0]
            .map(|selected| {
                std::iter::once(senses[selected].clone())
                    .chain(
                        senses
                            .iter()
                            .enumerate()
                            .filter(|(index, _)| *index != selected)
                            .map(|(_, sense)| sense.clone()),
                    )
                    .collect::<Vec<_>>()
            })
            .to_vec();
        assert_eq!(
            actual, expected,
            "a previously chosen rare meaning displaced a higher-priority alternative"
        );
    }

    #[test]
    fn a_novel_recomposition_cannot_reorder_the_other_reviewed_meanings() {
        let candidate = WordCandidate::with_senses(
            "bank",
            vec![
                Sense::tagged("common", "central"),
                Sense::plain("less common"),
                Sense::tagged("rare", "specialized"),
            ],
            2,
            true,
        );
        let revised = CardDraft::from_candidate(&candidate, 2, LanguagePair::new("en", "ru"))
            .recomposed("bank", "new interpretation", meta(), None)
            .recomposed("bank", "common", meta(), None);
        assert_eq!(
            revised.reviewed_senses(),
            &[
                Sense::tagged("common", "central"),
                Sense::plain("less common"),
                Sense::plain("new interpretation")
            ],
            "a replacement sense inherited an obsolete tag or reordered surviving alternatives"
        );
    }

    #[test]
    fn a_revision_promotes_a_normalized_alternative_without_losing_its_tag() {
        let candidate = WordCandidate::with_selected_senses(
            "canard",
            vec![
                Sense::plain("a duck"),
                Sense::tagged("a false report", "journalism"),
                Sense::plain("a newspaper hoax"),
            ],
            vec![0],
            true,
        );
        let revised = CardDraft::from_candidate(&candidate, 0, LanguagePair::new("en", "fr"))
            .with_revision(
                CardRevision::new("canard", "  A   FALSE REPORT  ", meta()),
                None,
            );
        assert_eq!(
            revised.reviewed_senses(),
            &[
                Sense::tagged("a false report", "journalism"),
                Sense::plain("a duck"),
                Sense::plain("a newspaper hoax"),
            ],
            "a normalized revision duplicated its reviewed alternative or discarded the alternative tag"
        );
    }

    #[test]
    fn a_revision_matching_the_selected_sense_keeps_canonical_text_and_tag() {
        let candidate = WordCandidate::with_selected_senses(
            "crever",
            vec![
                Sense::tagged("to die", "slang"),
                Sense::plain("to puncture"),
            ],
            vec![0],
            true,
        );
        let revised = CardDraft::from_candidate(&candidate, 0, LanguagePair::new("en", "fr"))
            .with_revision(CardRevision::new("crever", "  TO   DIE ", meta()), None);
        assert_eq!(
            revised.reviewed_senses(),
            &[
                Sense::tagged("to die", "slang"),
                Sense::plain("to puncture"),
            ],
            "a normalized revision rewrote the canonical selected sense or lost its tag"
        );
    }

    #[test]
    fn a_novel_recomposition_cannot_inherit_the_previous_sense_tag() {
        let candidate = WordCandidate::with_selected_senses(
            "crever",
            vec![
                Sense::tagged("to die", "slang"),
                Sense::plain("to puncture"),
            ],
            vec![0],
            true,
        );
        let revised = CardDraft::from_candidate(&candidate, 0, LanguagePair::new("en", "fr"))
            .recomposed("crever", "to stop operating", meta(), None);
        assert_eq!(
            revised.reviewed_senses(),
            &[
                Sense::plain("to stop operating"),
                Sense::plain("to puncture"),
            ],
            "a genuinely new correction inherited the tag of the replaced sense"
        );
    }

    #[test]
    fn a_revision_changing_the_term_cannot_inherit_a_matching_sense_tag() {
        let candidate = WordCandidate::with_selected_senses(
            "crever",
            vec![
                Sense::tagged("to die", "slang"),
                Sense::plain("to puncture"),
            ],
            vec![0],
            true,
        );
        let revised = CardDraft::from_candidate(&candidate, 0, LanguagePair::new("fr", "en"))
            .with_revision(CardRevision::new("mourir", "to die", meta()), None);
        assert_eq!(
            revised.reviewed_senses(),
            &[Sense::plain("to die")],
            "a different term inherited the previous word's tag or alternative meanings"
        );
    }

    #[test]
    fn a_recomposition_changing_the_term_cannot_keep_the_previous_words_alternatives() {
        let candidate = WordCandidate::with_selected_senses(
            "saw",
            vec![
                Sense::plain("past tense of see"),
                Sense::tagged("a cutting tool", "woodwork"),
            ],
            vec![0],
            true,
        );
        let revised = CardDraft::from_candidate(&candidate, 0, LanguagePair::new("en", "ru"))
            .recomposed("see", "to perceive with eyes", meta(), None);
        assert_eq!(
            revised.reviewed_senses(),
            &[Sense::plain("to perceive with eyes")],
            "a corrected word still carried an alternative belonging to its previous form"
        );
    }

    #[test]
    fn a_same_term_recomposition_keeps_the_promoted_alternatives_tag() {
        let candidate = WordCandidate::with_selected_senses(
            "canard",
            vec![
                Sense::plain("a duck"),
                Sense::tagged("a false report", "journalism"),
                Sense::plain("a newspaper hoax"),
            ],
            vec![0],
            true,
        );
        let revised = CardDraft::from_candidate(&candidate, 0, LanguagePair::new("fr", "en"))
            .recomposed("canard", "  A   FALSE REPORT ", meta(), None);
        assert_eq!(
            revised.reviewed_senses(),
            &[
                Sense::tagged("a false report", "journalism"),
                Sense::plain("a duck"),
                Sense::plain("a newspaper hoax"),
            ],
            "a same-word correction lost the reviewed alternatives or the promoted sense tag"
        );
    }
}
