use super::pair::LanguagePair;

/// Artifact type produced for each card.
///
/// `Meta` is the rich text payload generated by the Pro Gemini pass before any
/// media artifact runs. Scene/Picture/Sound depend on it because they consume
/// the natural-language `target_sentence` to draw, illustrate, and speak.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Artifact {
    Meta,
    Scene,
    Picture,
    Sound,
}

impl Artifact {
    /// Return the stable label used in progress output.
    pub fn label(&self) -> &'static str {
        match self {
            Artifact::Meta => "meta",
            Artifact::Scene => "scene",
            Artifact::Picture => "picture",
            Artifact::Sound => "sound",
        }
    }
}

/// File metadata attached to one completed artifact.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ArtifactFile {
    name: String,
    path: std::path::PathBuf,
    size: String,
    cached: bool,
}

impl ArtifactFile {
    /// Create one artifact file descriptor with full filesystem path.
    pub fn new(
        name: impl Into<String>,
        path: impl Into<std::path::PathBuf>,
        size: impl Into<String>,
        cached: bool,
    ) -> Self {
        Self {
            name: name.into(),
            path: path.into(),
            size: size.into(),
            cached,
        }
    }

    /// Return the display filename.
    pub fn name(&self) -> &str {
        self.name.as_str()
    }

    /// Return the absolute filesystem path for this artifact, if any. Used by
    /// the click handler to open the artifact with the system default app.
    pub fn path(&self) -> &std::path::Path {
        self.path.as_path()
    }

    /// Return the human-readable file size.
    pub fn size(&self) -> &str {
        self.size.as_str()
    }

    /// Return whether this artifact came from cache.
    pub fn cached(&self) -> bool {
        self.cached
    }
}

/// Number of attempts already spent versus the absolute cap.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct AttemptTally {
    done: u8,
    ceiling: u8,
}

impl AttemptTally {
    /// Start one tally with an explicit ceiling.
    pub fn new(ceiling: u8) -> Self {
        Self { done: 0, ceiling }
    }

    /// Return the number of attempts already spent.
    pub fn done(&self) -> u8 {
        self.done
    }

    /// Return the ceiling (typically 3).
    pub fn ceiling(&self) -> u8 {
        self.ceiling
    }

    /// Return whether the artifact has run out of retry budget.
    pub fn exhausted(&self) -> bool {
        self.done >= self.ceiling
    }

    /// Record one more attempt.
    pub fn spent(self) -> Self {
        let next = self.done.saturating_add(1);
        Self {
            done: next.min(self.ceiling),
            ceiling: self.ceiling,
        }
    }
}

/// Per-artifact state for one card.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ArtifactSlot {
    kind: Artifact,
    ready: bool,
    discarded: bool,
    tally: AttemptTally,
    file: Option<ArtifactFile>,
}

impl ArtifactSlot {
    /// Create one fresh slot for the given artifact kind.
    pub fn fresh(kind: Artifact) -> Self {
        Self {
            kind,
            ready: false,
            discarded: false,
            tally: AttemptTally::new(3),
            file: None,
        }
    }

    /// Return the artifact kind.
    pub fn kind(&self) -> Artifact {
        self.kind
    }

    /// Return whether the artifact is ready.
    pub fn ready(&self) -> bool {
        self.ready
    }

    /// Return whether this artifact was explicitly discarded by the user.
    pub fn discarded(&self) -> bool {
        self.discarded
    }

    /// Return whether this slot no longer needs queue work.
    pub fn complete(&self) -> bool {
        self.ready || self.discarded || self.failed_terminally()
    }

    /// Return the attempt tally.
    pub fn tally(&self) -> AttemptTally {
        self.tally
    }

    /// Return completed artifact file metadata, if available.
    pub fn file(&self) -> Option<&ArtifactFile> {
        self.file.as_ref()
    }

    /// Return the slot as ready.
    pub fn succeeded(mut self) -> Self {
        self.ready = true;
        self.discarded = false;
        self
    }

    /// Return the slot as ready with file metadata.
    pub fn succeeded_with(mut self, file: ArtifactFile) -> Self {
        self.ready = true;
        self.discarded = false;
        self.file = Some(file);
        self
    }

    /// Return the slot after a failed attempt.
    pub fn attempted(mut self) -> Self {
        self.tally = self.tally.spent();
        self
    }

    /// Return the slot as explicitly discarded by the user.
    pub fn discard(mut self) -> Self {
        self.ready = false;
        self.discarded = true;
        self.file = None;
        self
    }

    /// Return whether retry budget has been exhausted without success.
    pub fn failed_terminally(&self) -> bool {
        !self.ready && !self.discarded && self.tally.exhausted()
    }
}

/// The four per-card artifact slots bundled together.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CardArtifacts {
    meta: ArtifactSlot,
    scene: ArtifactSlot,
    picture: ArtifactSlot,
    sound: ArtifactSlot,
}

impl Default for CardArtifacts {
    /// Return four fresh slots for a new card.
    fn default() -> Self {
        Self {
            meta: ArtifactSlot::fresh(Artifact::Meta),
            scene: ArtifactSlot::fresh(Artifact::Scene),
            picture: ArtifactSlot::fresh(Artifact::Picture),
            sound: ArtifactSlot::fresh(Artifact::Sound),
        }
    }
}

impl CardArtifacts {
    /// Compose one artifacts bundle from four explicit slots.
    pub fn from_parts(
        meta: ArtifactSlot,
        scene: ArtifactSlot,
        picture: ArtifactSlot,
        sound: ArtifactSlot,
    ) -> Self {
        Self {
            meta,
            scene,
            picture,
            sound,
        }
    }

    /// Return the slot for `Artifact::Meta`.
    pub fn meta(&self) -> &ArtifactSlot {
        &self.meta
    }

    /// Return the slot for `Artifact::Scene`.
    pub fn scene(&self) -> &ArtifactSlot {
        &self.scene
    }

    /// Return the slot for `Artifact::Picture`.
    pub fn picture(&self) -> &ArtifactSlot {
        &self.picture
    }

    /// Return the slot for `Artifact::Sound`.
    pub fn sound(&self) -> &ArtifactSlot {
        &self.sound
    }

    /// Return whether every artifact is ready.
    pub fn all_ready(&self) -> bool {
        self.meta.ready() && self.scene.ready() && self.picture.ready() && self.sound.ready()
    }

    /// Return whether any artifact failed terminally.
    pub fn has_failed(&self) -> bool {
        self.meta.failed_terminally()
            || self.scene.failed_terminally()
            || self.picture.failed_terminally()
            || self.sound.failed_terminally()
    }
}

/// The rich card content produced by the Pro Gemini meta-generation pass.
///
/// Mirrors the `VocabularyEntry` schema. Filled once per draft after the user
/// confirms the understanding pass, and updated when the user opens
/// `change this card` to refine a single card.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CardMeta {
    pronunciation: String,
    transcription: String,
    meaning: String,
    importance: u8,
    source_sentence: String,
    source_highlight: String,
    source_hint: String,
    source_context: String,
    target_sentence: String,
}

impl CardMeta {
    /// Create one card meta. Caller is responsible for validating that
    /// `source_highlight` is a substring of `source_sentence`.
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        pronunciation: impl Into<String>,
        transcription: impl Into<String>,
        meaning: impl Into<String>,
        importance: u8,
        source_sentence: impl Into<String>,
        source_highlight: impl Into<String>,
        source_hint: impl Into<String>,
        source_context: impl Into<String>,
        target_sentence: impl Into<String>,
    ) -> Self {
        Self {
            pronunciation: pronunciation.into(),
            transcription: transcription.into(),
            meaning: meaning.into(),
            importance,
            source_sentence: source_sentence.into(),
            source_highlight: source_highlight.into(),
            source_hint: source_hint.into(),
            source_context: source_context.into(),
            target_sentence: target_sentence.into(),
        }
    }

    /// Return the IPA transcription of the term.
    pub fn pronunciation(&self) -> &str {
        self.pronunciation.as_str()
    }

    /// Return the IPA transcription of the full target sentence.
    pub fn transcription(&self) -> &str {
        self.transcription.as_str()
    }

    /// Return the source-language translation of the term.
    pub fn meaning(&self) -> &str {
        self.meaning.as_str()
    }

    /// Return the importance score (1..=10).
    pub fn importance(&self) -> u8 {
        self.importance
    }

    /// Return the source-language translation of the target sentence.
    pub fn source_sentence(&self) -> &str {
        self.source_sentence.as_str()
    }

    /// Return the substring of `source_sentence` that translates the term.
    pub fn source_highlight(&self) -> &str {
        self.source_highlight.as_str()
    }

    /// Return the one-sentence memory cue in source language.
    pub fn source_hint(&self) -> &str {
        self.source_hint.as_str()
    }

    /// Return the multi-sentence usage explanation in source language.
    pub fn source_context(&self) -> &str {
        self.source_context.as_str()
    }

    /// Return the natural example sentence in target language.
    pub fn target_sentence(&self) -> &str {
        self.target_sentence.as_str()
    }
}

/// One card draft inside the current batch.
///
/// `meta` starts as `None` and is filled by the Pro Gemini meta pass that runs
/// before scene/picture/sound. The bridge to `VocabularyEntry` requires a meta.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CardDraft {
    term: String,
    understanding: String,
    pair: LanguagePair,
    meta: Option<CardMeta>,
    artifacts: CardArtifacts,
}

impl CardDraft {
    /// Create one draft with no meta yet.
    pub fn new(
        term: impl Into<String>,
        understanding: impl Into<String>,
        pair: LanguagePair,
    ) -> Self {
        Self {
            term: term.into(),
            understanding: understanding.into(),
            pair,
            meta: None,
            artifacts: CardArtifacts::default(),
        }
    }

    /// Return the primary term.
    pub fn term(&self) -> &str {
        self.term.as_str()
    }

    /// Return the understanding sentence carried over from the intake pass.
    pub fn understanding(&self) -> &str {
        self.understanding.as_str()
    }

    /// Return the language pair locked into the card.
    pub fn pair(&self) -> &LanguagePair {
        &self.pair
    }

    /// Return the rich meta if it has been generated.
    pub fn meta(&self) -> Option<&CardMeta> {
        self.meta.as_ref()
    }

    /// Return the per-artifact state.
    pub fn artifacts(&self) -> &CardArtifacts {
        &self.artifacts
    }

    /// Return the draft with the rich meta installed (after the Pro pass).
    /// Marks the Meta artifact slot as ready so the engine moves on to media
    /// steps. When `file` is provided the slot keeps a clickable file handle so
    /// the user can open the persisted JSON from the step list.
    pub fn with_meta(self, meta: CardMeta, file: Option<ArtifactFile>) -> Self {
        let meta_slot = match file {
            Some(file) => self.artifacts.meta().clone().succeeded_with(file),
            None => self.artifacts.meta().clone().succeeded(),
        };
        let artifacts = CardArtifacts::from_parts(
            meta_slot,
            self.artifacts.scene().clone(),
            self.artifacts.picture().clone(),
            self.artifacts.sound().clone(),
        );
        Self {
            term: self.term,
            understanding: self.understanding,
            pair: self.pair,
            meta: Some(meta),
            artifacts,
        }
    }

    /// Return the draft after a per-card correction.
    ///
    /// The correction may rewrite the term (typo fix), the understanding
    /// (sense or form change), and the rich meta. Artifacts reset because
    /// scene/picture/sound depend on the meta. When the caller has already
    /// persisted the new meta to disk, the resulting `ArtifactFile` lands on
    /// the meta slot so the meta row keeps its clickable file label.
    pub fn recomposed(
        self,
        term: impl Into<String>,
        understanding: impl Into<String>,
        meta: CardMeta,
        file: Option<ArtifactFile>,
    ) -> Self {
        let meta_slot = match file {
            Some(file) => ArtifactSlot::fresh(Artifact::Meta).succeeded_with(file),
            None => ArtifactSlot::fresh(Artifact::Meta).succeeded(),
        };
        let artifacts = CardArtifacts::from_parts(
            meta_slot,
            ArtifactSlot::fresh(Artifact::Scene),
            ArtifactSlot::fresh(Artifact::Picture),
            ArtifactSlot::fresh(Artifact::Sound),
        );
        Self {
            term: term.into(),
            understanding: understanding.into(),
            pair: self.pair,
            meta: Some(meta),
            artifacts,
        }
    }

    /// Return the draft with a different artifacts bundle (for retry/success events).
    pub fn with_artifacts(self, artifacts: CardArtifacts) -> Self {
        Self {
            term: self.term,
            understanding: self.understanding,
            pair: self.pair,
            meta: self.meta,
            artifacts,
        }
    }
}
