use anyhow::Result;
use serde::{Deserialize, Serialize};

use super::GenerationCost;
use super::attempt::{ARTIFACT_ATTEMPT_CEILING, AttemptFault, AttemptLog, AttemptTally};
use super::pair::LanguagePair;

/// Artifact type produced for each card.
///
/// `Meta` is the rich text payload generated by the Gemini card pass before any
/// media artifact runs. Scene/Picture/Sound depend on it because they consume
/// the natural-language `target_sentence` to draw, illustrate, and speak.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Artifact {
    Meta,
    Scene,
    Picture,
    Sound,
}

impl Artifact {
    /// Return the stable label used in progress output.
    pub fn label(&self) -> &'static str {
        match self {
            Artifact::Meta => "meta",
            Artifact::Scene => "scene",
            Artifact::Picture => "picture",
            Artifact::Sound => "sound",
        }
    }
}

/// One settled artifact operation: its result, own spend, related-stage spend,
/// and the diagnosed cause when it failed.
pub(crate) type AccountedAttempt<T> = (
    Result<T>,
    Option<GenerationCost>,
    Vec<(Artifact, GenerationCost)>,
    Option<AttemptFault>,
);

/// One artifact operation together with its primary and related stage spend.
pub struct ArtifactAttempt<T> {
    result: Result<T>,
    cost: Option<GenerationCost>,
    related: Vec<(Artifact, GenerationCost)>,
    fault: Option<AttemptFault>,
}

impl<T> ArtifactAttempt<T> {
    /// Create one operation outcome with spend incurred by this operation.
    #[must_use]
    pub fn new(result: Result<T>, cost: Option<GenerationCost>) -> Self {
        Self {
            result,
            cost,
            related: Vec::new(),
            fault: None,
        }
    }

    /// Create one operation outcome for which Gemini reported no spend.
    #[must_use]
    pub fn unmetered(result: Result<T>) -> Self {
        Self::new(result, None)
    }

    /// Return the operation error when the artifact was not produced.
    #[must_use]
    pub fn error(&self) -> Option<&anyhow::Error> {
        self.result.as_ref().err()
    }

    /// Return the diagnosed cause attached to this failed operation.
    #[must_use]
    pub fn fault(&self) -> Option<&AttemptFault> {
        self.fault.as_ref()
    }

    /// Attach incremental spend that belongs to a related artifact stage.
    #[must_use]
    pub(crate) fn with_related_cost(mut self, artifact: Artifact, cost: GenerationCost) -> Self {
        self.related.push((artifact, cost));
        self
    }

    /// Attach the diagnosed cause of one failed operation.
    #[must_use]
    pub fn with_fault(mut self, fault: AttemptFault) -> Self {
        self.fault = Some(fault);
        self
    }

    /// Consume the operation into its result and primary incremental spend.
    pub fn into_parts(self) -> (Result<T>, Option<GenerationCost>) {
        (self.result, self.cost)
    }

    /// Consume the operation into its result, stage-aware spend, and cause.
    pub(crate) fn into_accounted_parts(self) -> AccountedAttempt<T> {
        (self.result, self.cost, self.related, self.fault)
    }

    /// Consume the operation and discard its accounting metadata.
    pub fn into_result(self) -> Result<T> {
        self.result
    }
}

/// File metadata attached to one completed artifact.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ArtifactFile {
    name: String,
    path: std::path::PathBuf,
    size: String,
    cached: bool,
    cost: Option<GenerationCost>,
}

impl ArtifactFile {
    /// Create one artifact file descriptor with full filesystem path.
    pub fn new(
        name: impl Into<String>,
        path: impl Into<std::path::PathBuf>,
        size: impl Into<String>,
        cached: bool,
    ) -> Self {
        Self {
            name: name.into(),
            path: path.into(),
            size: size.into(),
            cached,
            cost: None,
        }
    }

    /// Return the display filename.
    pub fn name(&self) -> &str {
        self.name.as_str()
    }

    /// Return the absolute filesystem path for this artifact, if any. Used by
    /// the click handler to open the artifact with the system default app.
    pub fn path(&self) -> &std::path::Path {
        self.path.as_path()
    }

    /// Return the human-readable file size.
    pub fn size(&self) -> &str {
        self.size.as_str()
    }

    /// Return whether this artifact came from cache.
    pub fn cached(&self) -> bool {
        self.cached
    }

    /// Return the estimated Gemini cost attached to this artifact.
    pub fn cost(&self) -> Option<GenerationCost> {
        self.cost
    }

    /// Return the file with an estimated Gemini cost attached.
    pub fn with_cost(mut self, cost: GenerationCost) -> Self {
        self.cost = Some(cost);
        self
    }
}

/// Per-artifact state for one card.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ArtifactSlot {
    kind: Artifact,
    ready: bool,
    discarded: bool,
    attempts: AttemptLog,
    file: Option<ArtifactFile>,
    cost: Option<GenerationCost>,
}

impl ArtifactSlot {
    /// Create one fresh slot for the given artifact kind.
    pub fn fresh(kind: Artifact) -> Self {
        Self {
            kind,
            ready: false,
            discarded: false,
            attempts: AttemptLog::new(ARTIFACT_ATTEMPT_CEILING),
            file: None,
            cost: None,
        }
    }

    /// Return the artifact kind.
    pub fn kind(&self) -> Artifact {
        self.kind
    }

    /// Return whether the artifact is ready.
    pub fn ready(&self) -> bool {
        self.ready
    }

    /// Return whether this artifact was explicitly discarded by the user.
    pub fn discarded(&self) -> bool {
        self.discarded
    }

    /// Return whether this slot no longer needs queue work.
    pub fn complete(&self) -> bool {
        self.ready || self.discarded || self.failed_terminally()
    }

    /// Return the attempt tally.
    pub fn tally(&self) -> AttemptTally {
        self.attempts.tally()
    }

    /// Return why each spent attempt failed, in attempt order.
    pub fn faults(&self) -> &[AttemptFault] {
        self.attempts.faults()
    }

    /// Return why the most recently spent attempt failed.
    pub fn latest_fault(&self) -> Option<&AttemptFault> {
        self.attempts.latest()
    }

    /// Return completed artifact file metadata, if available.
    pub fn file(&self) -> Option<&ArtifactFile> {
        self.file.as_ref()
    }

    /// Return the estimated Gemini cost for this artifact slot.
    pub fn cost(&self) -> Option<GenerationCost> {
        self.cost
            .or_else(|| self.file.as_ref().and_then(ArtifactFile::cost))
    }

    /// Return the slot as ready.
    pub fn succeeded(mut self) -> Self {
        self.ready = true;
        self.discarded = false;
        self
    }

    /// Return the slot as ready with file metadata.
    pub fn succeeded_with(mut self, file: ArtifactFile) -> Self {
        self.ready = true;
        self.discarded = false;
        if let Some(cost) = file.cost() {
            self.cost = Some(cost);
        }
        self.file = Some(file);
        self
    }

    /// Return the slot after a failed attempt whose cause was not diagnosed.
    pub fn attempted(mut self) -> Self {
        self.attempts = self.attempts.spent();
        self
    }

    /// Return the slot after a failed attempt that failed for `fault`.
    pub fn faulted(mut self, fault: AttemptFault) -> Self {
        self.attempts = self.attempts.faulted(fault);
        self
    }

    /// Return the slot after a failed attempt with cumulative known spend.
    pub fn attempted_with(self, cost: GenerationCost) -> Self {
        self.attempted().accounted(cost)
    }

    /// Return a fresh retry slot while retaining already billed spend.
    pub fn retry(self) -> Self {
        let kind = self.kind;
        let cost = self.cost();
        let slot = Self::fresh(kind);
        match cost {
            Some(cost) => slot.accounted(cost),
            None => slot,
        }
    }

    /// Return the slot with its latest cumulative known spend.
    pub(crate) fn accounted(mut self, cost: GenerationCost) -> Self {
        self.cost = Some(cost);
        self
    }

    /// Return the slot as explicitly discarded by the user.
    pub fn discard(mut self) -> Self {
        let cost = self.cost();
        self.ready = false;
        self.discarded = true;
        self.file = None;
        self.cost = cost;
        self
    }

    /// Return whether retry budget has been exhausted without success.
    pub fn failed_terminally(&self) -> bool {
        !self.ready && !self.discarded && self.attempts.tally().exhausted()
    }
}

/// The four per-card artifact slots bundled together.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CardArtifacts {
    meta: ArtifactSlot,
    scene: ArtifactSlot,
    picture: ArtifactSlot,
    sound: ArtifactSlot,
}

/// Persistable per-artifact spend incurred by one generation session.
#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct ArtifactCosts {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    meta: Option<GenerationCost>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    scene: Option<GenerationCost>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    picture: Option<GenerationCost>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    sound: Option<GenerationCost>,
}

impl ArtifactCosts {
    /// Snapshot the session-scoped spend currently attached to artifact slots.
    #[must_use]
    pub fn from_artifacts(artifacts: &CardArtifacts) -> Self {
        Self {
            meta: artifacts.meta().cost(),
            scene: artifacts.scene().cost(),
            picture: artifacts.picture().cost(),
            sound: artifacts.sound().cost(),
        }
    }

    /// Return the session-scoped spend recorded for one artifact.
    #[must_use]
    pub fn cost(&self, artifact: Artifact) -> Option<GenerationCost> {
        match artifact {
            Artifact::Meta => self.meta,
            Artifact::Scene => self.scene,
            Artifact::Picture => self.picture,
            Artifact::Sound => self.sound,
        }
    }

    /// Return the costs after charging one artifact an additional amount.
    #[must_use]
    pub fn charged(mut self, artifact: Artifact, delta: GenerationCost) -> Self {
        let total = self.cost(artifact).unwrap_or_default() + delta;
        match artifact {
            Artifact::Meta => self.meta = Some(total),
            Artifact::Scene => self.scene = Some(total),
            Artifact::Picture => self.picture = Some(total),
            Artifact::Sound => self.sound = Some(total),
        }
        self
    }

    /// Return whether no provider spend is recorded for this session card.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.meta.is_none()
            && self.scene.is_none()
            && self.picture.is_none()
            && self.sound.is_none()
    }

    fn hydrate(&self, artifacts: CardArtifacts) -> CardArtifacts {
        CardArtifacts::from_parts(
            hydrate_cost(artifacts.meta().clone(), self.meta),
            hydrate_cost(artifacts.scene().clone(), self.scene),
            hydrate_cost(artifacts.picture().clone(), self.picture),
            hydrate_cost(artifacts.sound().clone(), self.sound),
        )
    }
}

fn hydrate_cost(slot: ArtifactSlot, cost: Option<GenerationCost>) -> ArtifactSlot {
    match cost {
        Some(cost) => slot.accounted(cost),
        None => slot,
    }
}

impl Default for CardArtifacts {
    /// Return four fresh slots for a new card.
    fn default() -> Self {
        Self {
            meta: ArtifactSlot::fresh(Artifact::Meta),
            scene: ArtifactSlot::fresh(Artifact::Scene),
            picture: ArtifactSlot::fresh(Artifact::Picture),
            sound: ArtifactSlot::fresh(Artifact::Sound),
        }
    }
}

impl CardArtifacts {
    /// Compose one artifacts bundle from four explicit slots.
    pub fn from_parts(
        meta: ArtifactSlot,
        scene: ArtifactSlot,
        picture: ArtifactSlot,
        sound: ArtifactSlot,
    ) -> Self {
        Self {
            meta,
            scene,
            picture,
            sound,
        }
    }

    /// Return the slot for `Artifact::Meta`.
    pub fn meta(&self) -> &ArtifactSlot {
        &self.meta
    }

    /// Return the slot for `Artifact::Scene`.
    pub fn scene(&self) -> &ArtifactSlot {
        &self.scene
    }

    /// Return the slot for `Artifact::Picture`.
    pub fn picture(&self) -> &ArtifactSlot {
        &self.picture
    }

    /// Return the slot for `Artifact::Sound`.
    pub fn sound(&self) -> &ArtifactSlot {
        &self.sound
    }

    /// Return whether every artifact is ready.
    pub fn all_ready(&self) -> bool {
        self.meta.ready() && self.scene.ready() && self.picture.ready() && self.sound.ready()
    }

    /// Return whether any artifact failed terminally.
    pub fn has_failed(&self) -> bool {
        self.meta.failed_terminally()
            || self.scene.failed_terminally()
            || self.picture.failed_terminally()
            || self.sound.failed_terminally()
    }

    /// Return the known Gemini cost across all artifact slots.
    pub fn cost(&self) -> Option<GenerationCost> {
        let costs = [self.meta(), self.scene(), self.picture(), self.sound()]
            .into_iter()
            .filter_map(ArtifactSlot::cost)
            .collect::<Vec<_>>();
        if costs.is_empty() {
            return None;
        }
        Some(costs.into_iter().sum())
    }
}

/// The rich card content produced by the Gemini meta-generation pass.
///
/// Mirrors the `VocabularyEntry` schema. Filled once per draft after the user
/// confirms the understanding pass, and updated when the user opens
/// `change this card` to refine a single card.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CardMeta {
    pronunciation: String,
    transcription: String,
    meaning: String,
    importance: u8,
    source_sentence: String,
    source_highlight: String,
    source_hint: String,
    source_context: String,
    target_sentence: String,
}

impl CardMeta {
    /// Create one card meta. Caller is responsible for validating that
    /// `source_highlight` is a substring of `source_sentence`.
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        pronunciation: impl Into<String>,
        transcription: impl Into<String>,
        meaning: impl Into<String>,
        importance: u8,
        source_sentence: impl Into<String>,
        source_highlight: impl Into<String>,
        source_hint: impl Into<String>,
        source_context: impl Into<String>,
        target_sentence: impl Into<String>,
    ) -> Self {
        Self {
            pronunciation: pronunciation.into(),
            transcription: transcription.into(),
            meaning: meaning.into(),
            importance,
            source_sentence: source_sentence.into(),
            source_highlight: source_highlight.into(),
            source_hint: source_hint.into(),
            source_context: source_context.into(),
            target_sentence: target_sentence.into(),
        }
    }

    /// Return the IPA transcription of the term.
    pub fn pronunciation(&self) -> &str {
        self.pronunciation.as_str()
    }

    /// Return the IPA transcription of the full target sentence.
    pub fn transcription(&self) -> &str {
        self.transcription.as_str()
    }

    /// Return the source-language translation of the term.
    pub fn meaning(&self) -> &str {
        self.meaning.as_str()
    }

    /// Return the importance score (1..=10).
    pub fn importance(&self) -> u8 {
        self.importance
    }

    /// Return the source-language translation of the target sentence.
    pub fn source_sentence(&self) -> &str {
        self.source_sentence.as_str()
    }

    /// Return the substring of `source_sentence` that translates the term.
    pub fn source_highlight(&self) -> &str {
        self.source_highlight.as_str()
    }

    /// Return the one-sentence memory cue in source language.
    pub fn source_hint(&self) -> &str {
        self.source_hint.as_str()
    }

    /// Return the multi-sentence usage explanation in source language.
    pub fn source_context(&self) -> &str {
        self.source_context.as_str()
    }

    /// Return the natural example sentence in target language.
    pub fn target_sentence(&self) -> &str {
        self.target_sentence.as_str()
    }
}

/// One card draft inside the current batch.
///
/// `meta` starts as `None` and is filled by the Gemini meta pass that runs
/// before scene/picture/sound. The bridge to `VocabularyEntry` requires a meta.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CardDraft {
    term: String,
    understanding: String,
    pair: LanguagePair,
    meta: Option<CardMeta>,
    artifacts: CardArtifacts,
}

impl CardDraft {
    /// Create one draft with no meta yet.
    pub fn new(
        term: impl Into<String>,
        understanding: impl Into<String>,
        pair: LanguagePair,
    ) -> Self {
        Self {
            term: term.into(),
            understanding: understanding.into(),
            pair,
            meta: None,
            artifacts: CardArtifacts::default(),
        }
    }

    /// Return the primary term.
    pub fn term(&self) -> &str {
        self.term.as_str()
    }

    /// Return the understanding sentence carried over from the intake pass.
    pub fn understanding(&self) -> &str {
        self.understanding.as_str()
    }

    /// Return the language pair locked into the card.
    pub fn pair(&self) -> &LanguagePair {
        &self.pair
    }

    /// Return the rich meta if it has been generated.
    pub fn meta(&self) -> Option<&CardMeta> {
        self.meta.as_ref()
    }

    /// Return the per-artifact state.
    pub fn artifacts(&self) -> &CardArtifacts {
        &self.artifacts
    }

    /// Return the draft with the rich meta installed after the Gemini pass.
    /// Marks the Meta artifact slot as ready so the engine moves on to media
    /// steps. When `file` is provided the slot keeps a clickable file handle so
    /// the user can open the persisted JSON from the step list.
    pub fn with_meta(self, meta: CardMeta, file: Option<ArtifactFile>) -> Self {
        let meta_slot = match file {
            Some(file) => self.artifacts.meta().clone().succeeded_with(file),
            None => self.artifacts.meta().clone().succeeded(),
        };
        let artifacts = CardArtifacts::from_parts(
            meta_slot,
            self.artifacts.scene().clone(),
            self.artifacts.picture().clone(),
            self.artifacts.sound().clone(),
        );
        Self {
            term: self.term,
            understanding: self.understanding,
            pair: self.pair,
            meta: Some(meta),
            artifacts,
        }
    }

    /// Return the draft after a per-card correction.
    ///
    /// The correction may rewrite the term (typo fix), the understanding
    /// (sense or form change), and the rich meta. Artifacts reset because
    /// scene/picture/sound depend on the meta. When the caller has already
    /// persisted the new meta to disk, the resulting `ArtifactFile` lands on
    /// the meta slot so the meta row keeps its clickable file label.
    pub fn recomposed(
        self,
        term: impl Into<String>,
        understanding: impl Into<String>,
        meta: CardMeta,
        file: Option<ArtifactFile>,
    ) -> Self {
        let meta_slot = match file {
            Some(file) => ArtifactSlot::fresh(Artifact::Meta).succeeded_with(file),
            None => ArtifactSlot::fresh(Artifact::Meta).succeeded(),
        };
        let artifacts = CardArtifacts::from_parts(
            meta_slot,
            ArtifactSlot::fresh(Artifact::Scene),
            ArtifactSlot::fresh(Artifact::Picture),
            ArtifactSlot::fresh(Artifact::Sound),
        );
        Self {
            term: term.into(),
            understanding: understanding.into(),
            pair: self.pair,
            meta: Some(meta),
            artifacts,
        }
    }

    /// Return the draft with a different artifacts bundle (for retry/success events).
    pub fn with_artifacts(self, artifacts: CardArtifacts) -> Self {
        Self {
            term: self.term,
            understanding: self.understanding,
            pair: self.pair,
            meta: self.meta,
            artifacts,
        }
    }

    /// Return the draft with persisted session-scoped artifact spend restored.
    #[must_use]
    pub fn with_costs(self, costs: ArtifactCosts) -> Self {
        let artifacts = costs.hydrate(self.artifacts);
        Self {
            term: self.term,
            understanding: self.understanding,
            pair: self.pair,
            meta: self.meta,
            artifacts,
        }
    }
}
