#!/usr/bin/env bash
# encode.sh — deterministic, tunable encode of the README demo gif.
#
# Reads timings.conf (the single source of truth for section names and
# durations), assembles a frame sequence section by section, and writes:
#   - live/capture.gif          the final 25fps palettized gif
#   - timings.timeline.txt      a human-readable log: for every named action,
#                               its [start,end] second in the FINAL gif plus
#                               the raw source window it was sampled from.
#
# Tuning loop: read timings.timeline.txt, decide "shift this" / "squeeze that",
# edit the matching out_s (or src window) in timings.conf, re-run ./encode.sh.
#
# Requires: a raw recording at the path named by RAW below (default /tmp/raw.gif),
# and the static splice PNGs under live/.
set -euo pipefail
export LC_ALL=C

cd "$(dirname "$0")"
RAW="${RAW:-/tmp/raw.gif}"
CONF="${CONF:-timings.conf}"
OUT="${OUT:-live/capture.gif}"
TIMELINE="timings.timeline.txt"
FPS="${FPS:-25}"
# Finale fade knobs (kind=fade): the top "your files" strip brightens while the
# card list below the split line dims, over the fade window.
# Top strip: push contrast hard so the cream glyphs go bright-white while the
# near-black background stays black (brightens the letters, not the background).
TOP_CONTRAST="${TOP_CONTRAST:-1.65}"  # >1 makes text pop brighter, background darker
TOP_BRIGHT="${TOP_BRIGHT:-0.03}"      # tiny extra lift on the top strip
TOP_SAT="${TOP_SAT:-1.05}"            # eq saturation of the top strip
# List below: crush to pure black so only the top strip remains at the end.
BOT_CONTRAST="${BOT_CONTRAST:-1.0}"   # irrelevant once brightness drives it fully black
BOT_DARK="${BOT_DARK:--1.0}"          # -1.0 = the whole list goes to black
BOT_SAT="${BOT_SAT:-0.0}"             # eq saturation of the list
# Caption overlaid on the blacked-out area at the end (same VHS JetBrains Mono as the TUI).
CAPTION="${CAPTION:-live/caption.png}" # tight "↑ click and open" still; empty to disable
CAP_X="${CAP_X:-175}"                   # caption left edge in RAW (2x) pixels
CAP_Y="${CAP_Y:-350}"                  # caption top edge in RAW (2x) pixels
# Per-step subtitle badge (6th conf field on a window section): centered horizontally
# at STEP_CAP_Y, sits in the empty lower area without covering the TUI headers.
STEP_CAP_Y="${STEP_CAP_Y:-1460}"       # default step caption top edge in RAW (2x) pixels
FADE_S="${FADE_S:-0.3}"                # step caption fade in/out duration, output seconds
# Output knobs. The raw is recorded at 2x for crisp text; the gif is supersampled
# down to SCALE_W with lanczos (sharp small text), the hi-res original is kept full size.
COLORS="${COLORS:-256}"            # gif palette size — higher = smoother tone, bigger file
DITHER="${DITHER:-none}"           # gif dithering — none keeps letter edges crisp
SCALE_W="${SCALE_W:-1200}"         # gif output width (height auto, aspect kept); 0 = native
HIRES="${HIRES:-live/capture.hires.mp4}"  # opt-in hi-res master path (MAKE_HIRES=1); local-only, not committed
HIRES_CRF="${HIRES_CRF:-8}"        # x264 quality for the hi-res original — lower = sharper/bigger
# Loop-wrap fades: the gif loops, so the last finale frame would otherwise hard-cut
# back to the opening frame. Fade the tail out to black and the head in from black so
# the wrap reads as one breath (both ends are already near-black).
END_FADE_S="${END_FADE_S:-0.6}"    # fade the final frame out to black at the very end
START_FADE_S="${START_FADE_S:-0.4}"  # fade the first frame in from black
SEQ="$(mktemp -d)"
[ "${KEEP:-0}" = "1" ] || trap 'rm -rf "$SEQ"' EXIT
[ "${KEEP:-0}" = "1" ] && echo "encode.sh: keeping frame sequence at $SEQ"

[ -f "$RAW" ] || { echo "encode.sh: raw recording not found at $RAW" >&2; exit 1; }
[ -f "$CONF" ] || { echo "encode.sh: $CONF not found" >&2; exit 1; }

round() { awk -v x="$1" 'BEGIN{printf "%d", (x*1 + 0.5)}'; }
RAW_W="$(ffprobe -v error -select_streams v:0 -show_entries stream=width -of default=nk=1:nw=1 "$RAW")"
RAW_H="$(ffprobe -v error -select_streams v:0 -show_entries stream=height -of default=nk=1:nw=1 "$RAW")"

seq_i=0
out_frame=0
: > "$TIMELINE"
{
  printf '# kamishibai demo gif timeline — generated by encode.sh, do not edit by hand.\n'
  printf '# Edit timings.conf instead, then re-run ./encode.sh.\n'
  printf '# output fps = %s\n\n' "$FPS"
  printf '%-22s %-7s %10s %10s %9s   %s\n' "action" "kind" "out_start" "out_end" "out_dur" "source"
  printf '%-22s %-7s %10s %10s %9s   %s\n' "----------------------" "-------" "----------" "----------" "---------" "----------------------"
} >> "$TIMELINE"

while IFS='|' read -r id kind a b out_s cap; do
  id="$(echo "$id" | xargs)"; kind="$(echo "$kind" | xargs)"
  a="$(echo "$a" | xargs)";   b="$(echo "$b" | xargs)"; out_s="$(echo "$out_s" | xargs)"
  cap="$(echo "${cap:-}" | xargs)"
  capfile="$(echo "$cap" | cut -d, -f1)"
  capx="$(echo "$cap" | cut -d, -f2)"
  capy="$(echo "$cap" | cut -d, -f3)"
  capfin="$(echo "$cap" | cut -d, -f4)"
  capfout="$(echo "$cap" | cut -d, -f5)"
  case "$id" in ''|'#'*) continue;; esac

  nframes="$(round "$(awk -v s="$out_s" -v f="$FPS" 'BEGIN{print s*f}')")"
  [ "$nframes" -lt 1 ] && nframes=1
  start_frame=$out_frame

  if [ "$kind" = "splice" ]; then
    src_desc="splice $a"
    [ -f "$a" ] || { echo "encode.sh: splice png not found: $a" >&2; exit 1; }
    for _ in $(seq 1 "$nframes"); do
      cp "$a" "$(printf '%s/%05d.png' "$SEQ" "$seq_i")"; seq_i=$((seq_i+1))
    done
  elif [ "$kind" = "window" ]; then
    dur="$(awk -v a="$a" -v b="$b" 'BEGIN{print b-a}')"
    rate="$(awk -v n="$nframes" -v d="$dur" 'BEGIN{print (d>0)? n/d : 25}')"
    src_desc="raw ${a}s → ${b}s  (${dur}s @ ${rate}fps)"
    [ -n "$capfile" ] && src_desc="$src_desc  + caption $capfile"
    tmp="$(mktemp -d)"
    if [ -n "$capfile" ] && [ -f "$capfile" ]; then
      cw="$(ffprobe -v error -select_streams v:0 -show_entries stream=width -of default=nk=1:nw=1 "$capfile")"
      case "$capx" in ''|c|C) cx="$(awk -v w="$RAW_W" -v c="$cw" 'BEGIN{printf "%d",(w-c)/2}')";; *) cx="$capx";; esac
      cy="${capy:-$STEP_CAP_Y}"
      end="$(awk -v a="$a" -v d="$dur" 'BEGIN{print a+d}')"
      # per-caption fade in/out, OUTPUT seconds (blank = default FADE_S, 0 = no fade).
      # Setting fade-out to 0 holds the badge solid to the section end so it can carry
      # into the next section (which re-overlays it with fade-in 0 to continue seamlessly).
      ofin="${capfin:-$FADE_S}"; [ -z "$ofin" ] && ofin="$FADE_S"
      ofout="${capfout:-$FADE_S}"; [ -z "$ofout" ] && ofout="$FADE_S"
      capflt="format=yuva420p"
      if awk -v v="$ofin" 'BEGIN{exit !(v>0)}'; then
        fid="$(awk -v f="$ofin" -v d="$dur" -v o="$out_s" 'BEGIN{printf "%.4f", f*d/o}')"
        capflt="${capflt},fade=t=in:st=0:d=${fid}:alpha=1"
      fi
      if awk -v v="$ofout" 'BEGIN{exit !(v>0)}'; then
        fod="$(awk -v f="$ofout" -v d="$dur" -v o="$out_s" 'BEGIN{printf "%.4f", f*d/o}')"
        fos="$(awk -v d="$dur" -v fod="$fod" 'BEGIN{printf "%.4f", d-fod}')"
        capflt="${capflt},fade=t=out:st=${fos}:d=${fod}:alpha=1"
      fi
      ffmpeg -nostdin -y -loglevel error -i "$RAW" -loop 1 -i "$capfile" \
        -filter_complex "[0:v]trim=start=${a}:end=${end},setpts=PTS-STARTPTS,fps=${rate}[v];[1:v]${capflt}[c];[v][c]overlay=${cx}:${cy}:shortest=1" \
        "$tmp/w-%04d.png"
    else
      ffmpeg -nostdin -y -loglevel error -i "$RAW" -ss "$a" -t "$dur" -vf "fps=$rate" "$tmp/w-%04d.png"
    fi
    frames=()
    while IFS= read -r line; do frames+=("$line"); done < <(ls "$tmp"/w-*.png | sort)
    got="${#frames[@]}"
    [ "$got" -eq 0 ] && { echo "encode.sh: no frames extracted for $id" >&2; exit 1; }
    for k in $(seq 0 $((nframes-1))); do
      idx=$k; [ "$idx" -ge "$got" ] && idx=$((got-1))
      cp "${frames[$idx]}" "$(printf '%s/%05d.png' "$SEQ" "$seq_i")"; seq_i=$((seq_i+1))
    done
    rm -rf "$tmp"
  elif [ "$kind" = "fade" ]; then
    # a = still png ; b = "split_y,hold_s,fade_s,endhold_s" ; out_s = total (timeline only)
    #   holds the still hold_s, fast-fades to the end state over fade_s (list crushed to
    #   black, "click and open" caption fading in over the artifacts), then holds endhold_s.
    [ -f "$a" ] || { echo "encode.sh: fade png not found: $a" >&2; exit 1; }
    sy="$(echo "$b"  | cut -d, -f1)"
    hs="$(echo "$b"  | cut -d, -f2)"
    fs="$(echo "$b"  | cut -d, -f3)"
    es="$(echo "$b"  | cut -d, -f4)"; [ -z "$es" ] && es=0
    hold_n="$(round "$(awk -v s="$hs" -v f="$FPS" 'BEGIN{print s*f}')")"
    fade_n="$(round "$(awk -v s="$fs" -v f="$FPS" 'BEGIN{print s*f}')")"; [ "$fade_n" -lt 1 ] && fade_n=1
    end_n="$(round "$(awk -v s="$es" -v f="$FPS" 'BEGIN{print s*f}')")"
    nframes=$((hold_n + fade_n + end_n))
    src_desc="fade $a  (split y=$sy, hold ${hs}s, fade ${fs}s, hold-black ${es}s, caption)"
    tmp="$(mktemp -d)"
    H="$RAW_H"
    ffmpeg -nostdin -y -loglevel error -i "$a" -filter_complex \
      "[0:v]crop=${RAW_W}:${sy}:0:0,eq=contrast=${TOP_CONTRAST}:brightness=${TOP_BRIGHT}:saturation=${TOP_SAT}[t];\
       [0:v]crop=${RAW_W}:$((H-sy)):0:${sy},eq=contrast=${BOT_CONTRAST}:brightness=${BOT_DARK}:saturation=${BOT_SAT}[b];\
       [t][b]vstack=inputs=2" "$tmp/end.png"
    if [ -n "$CAPTION" ] && [ -f "$CAPTION" ]; then
      ffmpeg -nostdin -y -loglevel error -i "$tmp/end.png" -i "$CAPTION" -filter_complex \
        "[1:v]pad=${RAW_W}:${RAW_H}:${CAP_X}:${CAP_Y}:color=black[cap];[0:v][cap]blend=all_mode=lighten" "$tmp/endc.png"
    else
      cp "$tmp/end.png" "$tmp/endc.png"
    fi
    if [ "$hold_n" -ge 1 ]; then
      for _ in $(seq 1 "$hold_n"); do
        cp "$a" "$(printf '%s/%05d.png' "$SEQ" "$seq_i")"; seq_i=$((seq_i+1))
      done
    fi
    ffmpeg -nostdin -y -loglevel error -loop 1 -t "$fs" -i "$a" -loop 1 -t "$fs" -i "$tmp/end.png" \
      -filter_complex "[0:v]fps=$FPS,format=rgb24[x];[1:v]fps=$FPS,format=rgb24[y];[x][y]xfade=transition=fade:duration=${fs}:offset=0,fps=$FPS" \
      "$tmp/x-%04d.png"
    xframes=()
    while IFS= read -r line; do xframes+=("$line"); done < <(ls "$tmp"/x-*.png | sort)
    xgot="${#xframes[@]}"
    [ "$xgot" -eq 0 ] && { echo "encode.sh: fade produced no frames for $id" >&2; exit 1; }
    for k in $(seq 0 $((fade_n-1))); do
      idx=$k; [ "$idx" -ge "$xgot" ] && idx=$((xgot-1))
      cp "${xframes[$idx]}" "$(printf '%s/%05d.png' "$SEQ" "$seq_i")"; seq_i=$((seq_i+1))
    done
    if [ "$end_n" -ge 1 ]; then
      for _ in $(seq 1 "$end_n"); do
        cp "$tmp/endc.png" "$(printf '%s/%05d.png' "$SEQ" "$seq_i")"; seq_i=$((seq_i+1))
      done
    fi
    rm -rf "$tmp"
  else
    echo "encode.sh: unknown kind '$kind' for section '$id'" >&2; exit 1
  fi

  out_frame=$((out_frame + nframes))
  os="$(awk -v f="$start_frame" -v r="$FPS" 'BEGIN{printf "%.2f", f/r}')"
  oe="$(awk -v f="$out_frame"   -v r="$FPS" 'BEGIN{printf "%.2f", f/r}')"
  od="$(awk -v n="$nframes"     -v r="$FPS" 'BEGIN{printf "%.2f", n/r}')"
  printf '%-22s %-7s %9ss %9ss %8ss   %s\n' "$id" "$kind" "$os" "$oe" "$od" "$src_desc" >> "$TIMELINE"
done < "$CONF"

total_s="$(awk -v f="$out_frame" -v r="$FPS" 'BEGIN{printf "%.2f", f/r}')"
printf '\n# total: %s frames = %ss\n' "$out_frame" "$total_s" >> "$TIMELINE"

# Loop-wrap fade chain (in from black at the head, out to black at the tail).
fout="$(awk -v t="$total_s" -v e="$END_FADE_S" 'BEGIN{printf "%.4f", t-e}')"
loopfade="fade=t=in:st=0:d=${START_FADE_S}:color=black,fade=t=out:st=${fout}:d=${END_FADE_S}:color=black"

# ffmpeg 8.1's image2 demuxer + paletteuse hits an "Internal bug" on long PNG
# sequences, so stage the frames through a lossless intermediate video first.
# Bake the loop-wrap fade in here so the gif (palettegen/paletteuse) and the mp4
# inherit the exact same faded frames — the two-pass gif path otherwise drops it.
ffmpeg -nostdin -y -loglevel error -framerate "$FPS" -i "$SEQ/%05d.png" \
  -vf "$loopfade" -c:v ffv1 "$SEQ/inter.mkv"

# Hi-res master is OPT-IN and local-only: a plain run leaves only the committed gif.
# Set MAKE_HIRES=1 to also write a full-resolution near-lossless mp4 next to it.
if [ "${MAKE_HIRES:-0}" = "1" ]; then
  ffmpeg -nostdin -y -loglevel error -i "$SEQ/inter.mkv" \
    -c:v libx264 -preset slow -crf "$HIRES_CRF" -pix_fmt yuv420p -movflags +faststart "$HIRES"
fi

# README gif: supersample down to SCALE_W with lanczos for crisp small text, then palettize.
scale_chain=""
[ "$SCALE_W" != "0" ] && scale_chain="scale=${SCALE_W}:-2:flags=lanczos,"
[ "${SKIP_GIF:-0}" = "1" ] || ffmpeg -nostdin -y -loglevel error -i "$SEQ/inter.mkv" \
  -filter_complex "[0:v]${scale_chain}split[a][b];[a]palettegen=max_colors=${COLORS}:stats_mode=full[p];[b][p]paletteuse=dither=${DITHER}" \
  -loop 0 "$OUT"

echo "encode.sh: wrote $OUT ($out_frame frames, ${total_s}s) and $TIMELINE"
if [ "${MAKE_HIRES:-0}" = "1" ]; then echo "encode.sh: wrote hi-res master $HIRES (local-only)"; fi
cat "$TIMELINE"
